# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Dev Blog by Zil Norvilis
email: zil@norvilis.com
description: >- # this means to ignore newlines until "baseurl:"
  My thoughts on Web Developing, Solopreneurship, Linux and other. Including notes to myself
  for easier and quicker developing.
baseurl: /dev-blog
url: http://zilton7.github.io
twitter_username: zilasino
github_username:  zilton7

# Build settings
theme: minimal-mistakes-jekyll
minimal_mistakes_skin: dark

plugins:
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-archives
  - jekyll-tagging

tag_page_layout: tag_page
tag_page_dir: tags

defaults:
  - scope:
      path: ''
      type: posts
    values:
      layout: posts
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
      toc: true
      enable_copy_code_button: true

jekyll-archives:
  enabled: [categories, tags]
  layouts:
    category: category
    tag: tag
  permalinks:
    tag: /tags/:name/
    category: /categories/:name/
